### ISSUE TITLE
Some Bloodmarch NPC sheets won't open

### ISSUE THREAD

**Issue by RidiaBledpetal** [Forbidden-Lands-FVTT/fbl-content-modules#29]
Many of the Bloodmarch sheets won't open when clicked on. Ashenstead NPCs seem to be especially affected by this issue, but other NPC sheets are also affected. I have attached a screenshot. Of the NPCs in this folder, only Liklaudos, Prunofilia, and Tordenost open when clicked on.
![image](https://github.com/user-attachments/assets/6a73c83d-b21e-4e26-aeab-fba9841f2400)

**Comment by tuirgin** [comment]
I'm seeing the same behavior. Attempting to access several of the Bloodmarch actors throws errors like this:
```
foundry.js:5826 Foundry VTT | Rendering ForbiddenLandsCharacterSheet
foundry.js:655 Error: An error occurred while rendering ForbiddenLandsCharacterSheet 26. Cannot read properties of undefined (reading 'capitalize')
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5795:13Caused by: TypeError: Cannot read properties of undefined (reading 'capitalize')
    at ForbiddenLandsCharacterSheet.computeSkills (forbidden-lands.js:44:21378)
    at ForbiddenLandsCharacterSheet.getData (forbidden-lands.js:44:25140)
    at async ForbiddenLandsCharacterSheet._render (foundry.js:5838:18)
    at async ForbiddenLandsCharacterSheet._render (foundry.js:6572:5)
    at async ForbiddenLandsCharacterSheet._render (foundry.js:7158:5)
onError @ foundry.js:655
(anonymous) @ foundry.js:5795
Promise.catch
render @ foundry.js:5793
_onClickEntryName @ foundry.js:73976
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

I exported a selection of the bugged actors and a working one. The thing that I notice in all of the bugged actors I checked is an extra "animal_handling" object in `system.skill` with a value, but no "label", "min", or "attribute" properties. Like this:

``` json
    "skill": {
      ...
      "animal-handling": {
        "label": "SKILL.ANIMAL_HANDLING",
        "value": 0,
        "min": 0,
        "attribute": "empathy"
      },
      "animal_handling": {
        "value": 3
      }
    },
```
Others have a similar situation with "sleight_of_hand".

Using `foundryvtt-cli` I removed these duplicate partial skill objects and it looks like that took care of it.
## System
This is on:
- Foundry: 12.331
- Forbidden Lands: 12.1.0
- Forbidden Lands - Bloodmarch: 2.0.0
## Affected Actors
### Adventure Sites
#### Ashenstead
- Gerbera
- Merdekai
- Mommodar
- Mongello
- Siltellos
#### Bann Guelder
- Mergonella
- Meskella
- Verdegas
#### Oxengelder
- Kalemes
#### Salterstay
- Arjebee
### Taregyll
- Antmar Stickyfingers
- Jagra
- Kurmena
### Tribolia of the Kogler
- Aramalia
- Bydmer
#### Watch of the Sisters
- D'irae
- Vheilor
### Key Players
- Colonel Grudenstaal
- Fiena Fromelei
- Selligar Horne
### NPCs
- Clan Chieftan
- Clan Rider
- Egressor
- Ironbrow
- Penite, Goblin Peddler
- Penite, Halfling Druid
### Random Encounters
- Aslene Rider
- Kromabella
- Mengendorm
